name: Tests
on: [push]
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
          # key: ${{ secrets.KEY }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd hackathon202210/metrics
          git pull
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/hackathon.rsa outscale@217.75.164.121 "sudo systemctl restart app1"
          ./start.sh
